### ISSUE TITLE
Unbound not working anymore

### ISSUE THREAD

**Issue by pochacho99** [chriscrowe/docker-pihole-unbound#47]
Configuring Upstream DNS server Custom 1 (IPV4) = 127.0.0.1#5335 to use unbound was working fine in v5.7, but after v5.8 unbound is no longer working.

**Comment by paulhutchings** [comment]
I know there's been some issues with the `v5.8` pihole image. [It's supposedly been fixed and they plan on pushing out a re-tag soon](https://github.com/pi-hole/docker-pi-hole/issues/834#issuecomment-821801370). Not sure if it is related but I would maybe try and rebuild this image manually once the fix is pushed just to see if it ends up solving the issue. At the very least it will help eliminate some variables.

**Comment by chriscrowe** [comment]
> I know there's been some issues with the `v5.8` pihole image. [It's supposedly been fixed and they plan on pushing out a re-tag soon](https://github.com/pi-hole/docker-pi-hole/issues/834#issuecomment-821801370). Not sure if it is related but I would maybe try and rebuild this image manually once the fix is pushed just to see if it ends up solving the issue. At the very least it will help eliminate some variables.

Thanks-- I subscribed to that issue and I'll build and push a new image once they push theirs.

**Comment by PromoFaux** [comment]
Retagged

**Comment by chriscrowe** [comment]
New `v5.8` image pushed!

**Comment by pochacho99** [comment]
> 
> 
> New `v5.8` image pushed!

Just pulled the new image but Unbound still not working, need to use another resolver. My dedicated Rpi Pihole is working fine with 127.0.0.1#5335

**Comment by chriscrowe** [comment]
Can you post the output from `docker-compose logs --tail=100`

**Comment by pochacho99** [comment]
I figured out the problem, I was trying to customise unbound.conf which caused some errors. I deleted the customizations and not unbound is working fine. The same customizations were working in your v5.7

 

I’ll play around again to see if I can get it working in v5.8
